import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy — ShuttleRank",
  description: "How ShuttleRank collects, uses, and protects your data.",
};

export default function PrivacyPage() {
  return (
    <div className="mx-auto max-w-2xl px-6 py-12 text-sm leading-6 text-foreground">
      <h1 className="mb-2 text-2xl font-semibold">Privacy Policy</h1>
      <p className="mb-8 text-muted-foreground">Last updated: September 5, 2026</p>

      <p className="mb-6">
        ShuttleRank (&ldquo;ShuttleRank,&rdquo; &ldquo;we,&rdquo; &ldquo;us&rdquo;) provides a badminton
        skill-rating and match-tracking service (the &ldquo;Service&rdquo;), available via our mobile
        app and website. This policy explains what information we collect, how we use it, and the
        choices you have.
      </p>

      <h2 className="mt-8 mb-2 text-lg font-semibold">1. Information we collect</h2>
      <p className="mb-2">When you create an account and use the Service, we collect:</p>
      <ul className="mb-4 list-disc space-y-1 pl-6">
        <li><strong>Account information</strong>: name, email address, and profile photo, provided via our authentication provider (Clerk) or entered by you.</li>
        <li><strong>Profile details you choose to add</strong>: gender, age, and a free-text location (e.g. city or club name). These are optional.</li>
        <li><strong>Match &amp; rating data</strong>: matches you submit or are added to, scores, opponents/partners, and the rating history that results.</li>
        <li><strong>Push notification tokens</strong>: if you enable notifications, we store a device token (via Expo) to deliver match-approval and result alerts. We do not collect precise device or location data alongside it.</li>
        <li><strong>Technical data</strong>: standard server logs (timestamps, request paths) generated by normal operation of the API, retained only for debugging and abuse prevention.</li>
      </ul>
      <p className="mb-4">
        We do not collect precise/GPS location, payment information, or contacts. We do not use
        third-party analytics or advertising trackers.
      </p>

      <h2 className="mt-8 mb-2 text-lg font-semibold">2. How we use your information</h2>
      <ul className="mb-4 list-disc space-y-1 pl-6">
        <li>To operate your account, compute and update your rating, and display leaderboards and match history.</li>
        <li>To notify you (by push notification or email) when a match involving you needs approval, or when a match is confirmed or disputed.</li>
        <li>To let other players find and add you when submitting a match (name-based search).</li>
        <li>To maintain the security and integrity of the Service.</li>
      </ul>

      <h2 className="mt-8 mb-2 text-lg font-semibold">3. What other players can see</h2>
      <p className="mb-4">
        ShuttleRank is a shared rating system, similar in spirit to DUPR or UBR. Your display name,
        profile photo, gender, self-reported age and location (if provided), rating/tier, and match
        history are visible to other users of the Service, since ratings and leaderboards are the
        core purpose of the product. Your email address and account identifiers are never shown to
        other users and are visible only to you and to ShuttleRank.
      </p>

      <h2 className="mt-8 mb-2 text-lg font-semibold">4. Third parties we work with</h2>
      <p className="mb-2">We use the following service providers to operate ShuttleRank. Each processes only what it needs to perform its function:</p>
      <ul className="mb-4 list-disc space-y-1 pl-6">
        <li><strong>Clerk</strong> — authentication and account/session management.</li>
        <li><strong>Resend</strong> — sends transactional emails (e.g. match-approval requests).</li>
        <li><strong>Expo</strong> — delivers push notifications to the mobile app.</li>
        <li><strong>Neon</strong> — hosts our production database.</li>
        <li><strong>Amazon Web Services (AWS)</strong> — hosts our API.</li>
        <li><strong>Vercel</strong> — hosts our website.</li>
      </ul>
      <p className="mb-4">
        We do not sell your personal information, and we do not share it with third parties for
        their own marketing purposes.
      </p>

      <h2 className="mt-8 mb-2 text-lg font-semibold">5. Data retention</h2>
      <p className="mb-4">
        We retain account and match data for as long as your account is active, since match history
        is required to compute your rating. If you delete your account, we delete or anonymize your
        personal information (name, email, profile fields) within a reasonable period, while
        aggregate/anonymized match results may be retained to preserve the rating integrity of other
        players&apos; matches.
      </p>

      <h2 className="mt-8 mb-2 text-lg font-semibold">6. Your choices</h2>
      <ul className="mb-4 list-disc space-y-1 pl-6">
        <li>You can edit or remove your age and location at any time from your profile.</li>
        <li>You can disable push notifications in your device or app settings.</li>
        <li>You can request deletion of your account and associated personal data by contacting us (below).</li>
      </ul>

      <h2 className="mt-8 mb-2 text-lg font-semibold">7. Children&apos;s privacy</h2>
      <p className="mb-4">
        ShuttleRank is not directed to children under 13, and we do not knowingly collect personal
        information from children under 13. If you believe a child has provided us with personal
        information, contact us and we will delete it.
      </p>

      <h2 className="mt-8 mb-2 text-lg font-semibold">8. Security</h2>
      <p className="mb-4">
        We use industry-standard measures to protect your information, including encrypted
        connections (HTTPS/TLS) and access controls on our database and infrastructure. No method of
        transmission or storage is 100% secure, but we work to protect your data and to correct any
        issues we identify promptly.
      </p>

      <h2 className="mt-8 mb-2 text-lg font-semibold">9. Changes to this policy</h2>
      <p className="mb-4">
        We may update this policy as the Service changes. We will update the &ldquo;Last updated&rdquo;
        date above when we do, and for material changes we will provide notice in the app.
      </p>

      <h2 className="mt-8 mb-2 text-lg font-semibold">10. Contact us</h2>
      <p className="mb-4">
        Questions about this policy or your data can be sent to{" "}
        <a className="underline" href="mailto:andrewxiaotoo@gmail.com">andrewxiaotoo@gmail.com</a>.
      </p>
    </div>
  );
}
